# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Luis\Desktop\python\Sql\telaLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(281, 295)
        MainWindow.setStyleSheet("background-color:gray;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEditUser = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditUser.setGeometry(QtCore.QRect(20, 20, 241, 31))
        self.lineEditUser.setStyleSheet("background-color:white;")
        self.lineEditUser.setObjectName("lineEditUser")
        self.lineEditPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPassword.setGeometry(QtCore.QRect(20, 70, 241, 31))
        self.lineEditPassword.setStyleSheet("background-color:white;")
        self.lineEditPassword.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.btnLogar = QtWidgets.QPushButton(self.centralwidget)
        self.btnLogar.setGeometry(QtCore.QRect(90, 110, 91, 31))
        self.btnLogar.setStyleSheet("font-size:15px;\n"
"background-color:green;")
        self.btnLogar.setObjectName("btnLogar")
        self.btnCad = QtWidgets.QPushButton(self.centralwidget)
        self.btnCad.setGeometry(QtCore.QRect(170, 190, 91, 31))
        self.btnCad.setStyleSheet("font-size:15px;\n"
"background-color:yellow;")
        self.btnCad.setObjectName("btnCad")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 200, 131, 16))
        self.label.setStyleSheet("font-size:15px;")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 281, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEditUser.setPlaceholderText(_translate("MainWindow", "Usuario"))
        self.lineEditPassword.setPlaceholderText(_translate("MainWindow", "Senha"))
        self.btnLogar.setText(_translate("MainWindow", "Login"))
        self.btnCad.setText(_translate("MainWindow", "Cadastrar"))
        self.label.setText(_translate("MainWindow", "Não possui usuario?"))
